name: Image Scan with build gate on SEV
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write

jobs:
  build-and-secure:
    name: CI Build with Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t prg-image -f Dockerfile .
          
      - name: Tag Image with Git Commit SHA
        run: |
          docker tag prg-image prg-image:${{ github.sha }}
    
      - name: Run Aqua scanner
        uses: docker://aquasec/aqua-scanner
        with:
          args: trivy fs --security-checks config,vuln,secret . --sast --severity CRITICAL
          # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          # To enable SAST scanning, add: --sast
          # To enable npm/dotnet non-lock file scanning, add: --package-json / --dotnet-proj
          # Just to Rerun the WFs
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          TRIVY_RUN_AS_PLUGIN: 'aqua'
          #SAST: 1
          TRIVY_DEBUG: 1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Tag Image for Docker Hub with SHA
        run: |
         docker tag prg-image ${{ secrets.DOCKERHUB_USERNAME }}/prg-image:${{ github.sha }}

      - name: Push Image to Docker Hub
        run: |
         docker push ${{ secrets.DOCKERHUB_USERNAME }}/prg-image:${{ github.sha }}

      - name: Trivy SBOM Generation
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          format: cyclonedx
          output: sbom.cdx.json

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.cdx.json
